# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.

# echo -n 'SN_TL_SP_SAP' | base64
# echo -n '291-317-318-322' | base64

apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  mongo-root-username: RE1fR1JfR01fR1M=
  mongo-root-password: MTQ0XzE1Nl8xNjRfMTY2
